server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/db
    username: usr
    password: pwd
  jpa:
    hibernate:
      ddl-auto: none      # on NE recrée pas le schéma; il vient des scripts d'init
    show-sql: true
    properties:
      hibernate.format_sql: true