name: CD – Docker Publish

on:
  workflow_run:
    workflows: ["CI devops 2025"]
    types: [completed]
    branches: [ main ]

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
          --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Backend
      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend-spring
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-backend:${{ github.sha }}

      # Database
      - name: Build & push database
        uses: docker/build-push-action@v6
        with:
          context: ./database
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/my-database:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/my-database:${{ github.sha }}

      # HTTPD (si présent)
      - name: Build & push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./httpd
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-httpd:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-httpd:${{ github.sha }}